### ISSUE TITLE
Spiral traversal of a matrix

### ISSUE THREAD

**Issue by raghavddps23** [raghavddps23/LearningGo-#1]
Add the solution for this problem in Go in the medium folder.

Example: Given an input like this
4 4
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16

Output:
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10

The first two lines indicating the number of rows and columns and the next line contains the elements row by row, we are supposed to print the spiral order traversal of the matrix.

Concepts required - Variables/If else statements/loops

**Comment by Naveenkhasyap** [comment]
Can I take this up @raghavddps23 ?

**Comment by Naveenkhasyap** [comment]
@raghavddps2 raised PR please check and merge accordingly. @raghavddps23

**Comment by raghavddps23** [comment]
Accepted your PR @Naveenkhasyap , Great work!
