### ISSUE TITLE
Add code to read and file and print onto the console in Go

### ISSUE THREAD

**Issue by raghavddps23** [raghavddps23/LearningGo-#13]
1. Read a file (text file) and print its contents into the terminal
2. Put this in the Easy folder.

**Comment by PankhudiB** [comment]
I can pick this up

**Comment by raghavddps23** [comment]
Sure, go ahead and raise a PR.

**Comment by raghavddps23** [comment]
I saw your Pull Request just now. Good work!
Good Work!
