### ISSUE TITLE
Search in a 2D matrix

### ISSUE THREAD

**Issue by raghavddps23** [raghavddps23/LearningGo-#4]
Write an efficient algorithm that searches for a value in an m x n matrix. This matrix has the following properties:
Put this in the medium folder.

Integers in each row are sorted from left to right.
The first integer of each row is greater than the last integer of the previous row.

Input and Output format
Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,50]], target = 3
Output: true

Write a program in go for the same

**Comment by vishal-wadhwa** [comment]
Can you assign me this?

**Comment by raghavddps23** [comment]
Sure @vishal-wadhwa , 
Go ahead and raise a PR.
The expected time complexity for this is O(log(n)) but even an n*log(n) solution works fine.
Feel free to solve in any of the way.

**Comment by vishal-wadhwa** [comment]
@raghavddps2 Added a O(logn) solution. Please check: https://github.com/raghavddps23/LearningGo-/pull/9
