### ISSUE TITLE
Add the Queue Data Structure

### ISSUE THREAD

**Issue by raghavddps23** [raghavddps23/LearningGo-#8]
Add the Queue Data structure in the Medium Folder.
For guide on how to get started, refer to the Stack Data Structure implemented in the Medium Folder

You need to create 2 files
1. One file implementing all the queue functions - enqueue/dequeue/is Empty/front 
2. Another file using the same Queue written in the previous file.

For understanding how a queue works, refer this article on GeeksForGeeks
https://www.geeksforgeeks.org/array-implementation-of-queue-simple/

**Comment by nazuk27** [comment]
Please assign this to me.
